menu:
  Home: /
  Archives: /archives
rss: /atom.xml

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: swiftcnorg

google_analytics:
favicon: /favicon.ico

default_github: swiftcn
default_displayname: SwiftCN
